services:
  caddy:
    environment:
      CADDY_GLOBAL_OPTIONS: |
        grace_period 10s
        default_sni ${SERVER_NAME}
    volumes:
      - ${STORAGE_BASE_PATH}/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - /var/log/caddy:/var/log/caddy

volumes:
  caddy-config:
  caddy-data: