name: Build and deploy website
on: [push]
jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Deploy to Digital Ocean droplet via SSH action
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          SERVER_NAME: ${{ secrets.SERVER_NAME }}
          MAILGUN_APIKEY: ${{ secrets.MAILGUN_APIKEY }}
          MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
          MAILGUN_FROM_WHO: ${{ secrets.MAILGUN_FROM_WHO }}
          MAILGUN_TO_WHO_NAME: ${{ secrets.MAILGUN_TO_WHO_NAME }}
          MAILGUN_TO_WHO: ${{ secrets.MAILGUN_TO_WHO }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          ALTCHA_HMAC_KEY: ${{ secrets.ALTCHA_HMAC_KEY }}
          UMAMI_WEBSITE_CODE: ${{ env.UMAMI_WEBSITE_CODE }}
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          command_timeout: 10m
          envs: DIGITALOCEAN_ACCESS_TOKEN,SERVER_NAME,MAILGUN_APIKEY,MAILGUN_DOMAIN,MAILGUN_FROM_WHO,MAILGUN_TO_WHO_NAME,MAILGUN_TO_WHO,POSTGRES_USER,POSTGRES_HOST,POSTGRES_DB,POSTGRES_PASSWORD,POSTGRES_PORT,ALTCHA_HMAC_KEY,UMAMI_WEBSITE_CODE
          script: |
            set -e
            cd /home/aboul/www/aboulbox.com
            git pull
            export SERVER_NAME=$SERVER_NAME
            export MAILGUN_APIKEY=$MAILGUN_APIKEY
            export MAILGUN_DOMAIN=$MAILGUN_DOMAIN
            export MAILGUN_FROM_WHO=$MAILGUN_FROM_WHO
            export MAILGUN_TO_WHO_NAME=$MAILGUN_TO_WHO_NAME
            export MAILGUN_TO_WHO=$MAILGUN_TO_WHO
            export POSTGRES_USER=$POSTGRES_USER
            export POSTGRES_HOST=$POSTGRES_HOST
            export POSTGRES_DB=$POSTGRES_DB
            export POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            export POSTGRES_PORT=$POSTGRES_PORT
            export ALTCHA_HMAC_KEY=$ALTCHA_HMAC_KEY
            export DATABASE_URL="postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/umami"
            export UMAMI_WEBSITE_CODE=$UMAMI_WEBSITE_CODE
            make down 
            make up-prod
